#!/usr/bin/env ruby

load File.join(File.dirname(__FILE__), '../lib/all.rb')
include Common

usage = <<-TEXT
Usage: ./postgres.rb -s <schema_name> -v <version> dbname

This will install the functions on <dbname>.

Arguments:

  -?|--help           Display description of usage.
  -h|--host=          The host name of the machine against which to run the script. Defaults to localhost.
  -p|--port=          The port of the running Postgres instance. Optional.
  -s|--schema_name=   The schema name under which to install the util functions. Defaults to "journal".
  -U|--username=      The postgres user to run the script as. Optional.
TEXT

opts = Trollop::options do
  banner <<-EOS
This will install the functions on <dbname>.

Usage:
    ./postgres-journaling [options] dbname
where [options] are:
EOS
  opt :host, 'The host name of the machine against which to run the script. Defaults to localhost.', :type => String, :default => 'localhost'
  opt :port, 'The port of the running Postgres instance.', :type => Integer
  opt :schema_name, 'The schema name under which to install the util functions. Defaults to "journal".', :type => String, :default => 'journal'
  opt :username, 'The postgres user to run the script as.', :type => String, :short => 'U'
end

version = opts[:version]
schema_name = opts[:schema_name]
dbname = ARGV[0]
if dbname.nil?
  tell 'Please specify a target database.'
else
  version = Version.read
  tell "Installing version [%s] on schema [%s]" % [version.to_version_string, schema_name]
  psql = Psql.new(dbname,
                 :username => opts[:username],
                 :host => opts[:host],
                 :port => opts[:port])
  query = psql.in_schema(schema_name) do
    File.read("scripts/postgres/install.sql").gsub("journal.", "#{schema_name}.")
  end
  success = psql.execute(query)
  tell "Journaling installed successfully into the #{schema_name} schema." if success
end